language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install pytest>=2.7.3 --upgrade
# command to run tests
script: py.test